"""
WhatsApp Bulk Report Sender
============================
A Streamlit app for professors to send personalized WhatsApp reports
to parents based on an uploaded Excel/CSV sheet — powered by pywhatkit.

Author  : Generated by Antigravity
License : MIT
"""

import time
import re

import pandas as pd
try:
    import pywhatkit
    PYWHATKIT_AVAILABLE = True
except Exception as e:
    PYWHATKIT_AVAILABLE = False
    PYWHATKIT_ERROR = str(e)
import streamlit as st

# ─────────────────────────────────────────────────────────────────────────────
# Page Configuration
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="📊 WhatsApp Bulk Report Sender",
    page_icon="📲",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────────────────────────────────────
# Custom CSS — clean, professional look
# ─────────────────────────────────────────────────────────────────────────────
st.markdown(
    """
    <style>
        /* App background */
        .stApp { background-color: #0f1117; }

        /* Sidebar */
        [data-testid="stSidebar"] {
            background-color: #1a1d27;
        }

        /* Section cards */
        .section-card {
            background: #1e2130;
            border-radius: 12px;
            padding: 24px 28px;
            margin-bottom: 20px;
            border: 1px solid #2e3250;
        }

        /* Column-insert buttons */
        .stButton > button {
            border-radius: 20px !important;
            font-size: 0.78rem !important;
            padding: 4px 12px !important;
            transition: all 0.2s ease;
        }

        /* Bold "Send" button */
        .send-btn > button {
            background: linear-gradient(135deg, #25D366, #128C7E) !important;
            color: white !important;
            font-weight: 700 !important;
            font-size: 1.05rem !important;
            padding: 12px 30px !important;
            border-radius: 10px !important;
            border: none !important;
            width: 100%;
        }
        .send-btn > button:hover {
            opacity: 0.9;
            transform: scale(1.02);
        }

        /* Preview box */
        .preview-box {
            background: #262a3d;
            border-left: 4px solid #25D366;
            border-radius: 8px;
            padding: 16px 20px;
            font-family: monospace;
            white-space: pre-wrap;
            word-wrap: break-word;
            color: #e0e0e0;
            min-height: 80px;
        }

        /* Step labels */
        .step-label {
            font-size: 0.72rem;
            letter-spacing: 0.1em;
            text-transform: uppercase;
            color: #7b8cde;
            font-weight: 600;
            margin-bottom: 4px;
        }

        /* Status badge */
        .status-ok   { color: #25D366; font-weight: 700; }
        .status-warn { color: #f0a500; font-weight: 700; }
        .status-err  { color: #e74c3c; font-weight: 700; }
    </style>
    """,
    unsafe_allow_html=True,
)

# ─────────────────────────────────────────────────────────────────────────────
# Session-state initialisation
# ─────────────────────────────────────────────────────────────────────────────
if "template" not in st.session_state:
    st.session_state.template = ""

if "df" not in st.session_state:
    st.session_state.df = None

# ─────────────────────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────────────────────

def load_dataframe(uploaded_file) -> pd.DataFrame:
    """Read an xlsx or csv file into a pandas DataFrame."""
    if uploaded_file.name.endswith(".csv"):
        return pd.read_csv(uploaded_file)
    return pd.read_excel(uploaded_file)


def build_message(template: str, row: pd.Series) -> str:
    """
    Replace every {Column_Name} placeholder in the template with the
    corresponding value from the row. Unknown placeholders are left intact.
    """
    def replacer(match):
        key = match.group(1).strip()
        if key in row.index:
            return str(row[key])
        return match.group(0)          # keep original if column not found

    return re.sub(r"\{([^}]+)\}", replacer, template)


def format_phone(raw) -> str:
    """
    Normalise a phone number to the E.164-like format expected by pywhatkit
    (e.g., '+919876543210'). Handles numbers stored as float/int by Excel.
    """
    phone = str(raw).strip()

    # Remove .0 that pandas adds when reading numeric cells as float
    if phone.endswith(".0"):
        phone = phone[:-2]

    # Strip spaces, dashes, parentheses
    phone = re.sub(r"[\s\-\(\)]", "", phone)

    # Ensure it starts with '+'
    if not phone.startswith("+"):
        phone = "+" + phone

    return phone


def validate_template(template: str, columns: list) -> list:
    """Return a list of {Placeholder} tokens in the template that don't match
    any column name — helpful for catching typos before sending."""
    placeholders = re.findall(r"\{([^}]+)\}", template)
    return [p for p in placeholders if p not in columns]


# ─────────────────────────────────────────────────────────────────────────────
# Sidebar — App info & instructions
# ─────────────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image(
        "https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg",
        width=60,
    )
    st.title("📊 Report Sender")
    st.caption("Automate personalised WhatsApp reports for parents — free, no API needed.")
    st.divider()

    st.markdown("### 📖 How to Use")
    st.markdown(
        """
1. **Upload** your Excel / CSV file.
2. **Build** your message template using the `{}` buttons to insert column names.
3. **Select** the column that holds the parent's phone number.
4. **Preview** the message for the first student.
5. Click **Send All Reports** and keep WhatsApp Web open in your browser.

> ⚠️ Make sure **WhatsApp Web** is already logged-in in your default browser before sending.
        """,
        unsafe_allow_html=False,
    )
    st.divider()
    st.markdown("#### ⚙️ Safety Settings")
    st.markdown(
        "- **15 s** browser open delay per message  \n"
        "- **20 s** gap between each send  \n"
        "- Tab auto-closes after sending"
    )


# ─────────────────────────────────────────────────────────────────────────────
# Main Layout
# ─────────────────────────────────────────────────────────────────────────────
st.title("📲 WhatsApp Bulk Report Sender")
st.caption(
    "Upload a student data sheet, craft a personalised message template, "
    "and send reports to every parent in one click."
)
st.divider()

# ════════════════════════════════════════════════════════════════════════════
# STEP 1 — File Upload
# ════════════════════════════════════════════════════════════════════════════
st.markdown('<p class="step-label">Step 1 — Upload Student Data</p>', unsafe_allow_html=True)
with st.container():
    uploaded_file = st.file_uploader(
        "Drop your Excel (.xlsx) or CSV file here",
        type=["xlsx", "xls", "csv"],
        help="Each row = one student. Column headers become template variables.",
    )

    if uploaded_file:
        try:
            df = load_dataframe(uploaded_file)
            st.session_state.df = df
            st.success(
                f"✅ File loaded — **{len(df)} rows**, **{len(df.columns)} columns** detected.",
                icon="📄",
            )

            # Show a quick preview of the data
            with st.expander("👀 Preview uploaded data (first 5 rows)", expanded=False):
                st.dataframe(df.head(5), use_container_width=True)

        except Exception as exc:
            st.error(f"❌ Could not read file: {exc}")
            st.session_state.df = None

st.divider()

# Only proceed if data is loaded
if st.session_state.df is not None:
    df: pd.DataFrame = st.session_state.df
    columns = df.columns.tolist()

    # ══════════════════════════════════════════════════════════════════════════
    # STEP 2 — Template Builder
    # ══════════════════════════════════════════════════════════════════════════
    st.markdown('<p class="step-label">Step 2 — Build Your Message Template</p>', unsafe_allow_html=True)

    col_left, col_right = st.columns([3, 2], gap="large")

    with col_left:
        st.markdown("**📝 Message Template**")
        st.caption(
            "Type your message below. Click a column-name button on the right "
            "to insert it as a `{Variable}` placeholder."
        )

        template_input = st.text_area(
            label="Message Template",
            value=st.session_state.template,
            height=260,
            placeholder=(
                "Example:\n\n"
                "Dear Parent,\n\n"
                "This is to inform you that {Student_Name} has scored:\n"
                "  • Python  : {Python_Marks}\n"
                "  • Maths   : {Maths_Marks}\n\n"
                "Please contact the institution for any queries.\n\n"
                "Regards,\nProf. Sharma"
            ),
            label_visibility="collapsed",
            key="template_area",
        )

        # Keep session state in sync
        st.session_state.template = template_input

    with col_right:
        st.markdown("**🏷️ Available Columns — click to insert**")
        st.caption("Each button appends `{ColumnName}` at the end of your template.")

        # Lay buttons in a 2-column mini grid
        btn_cols = st.columns(2)
        for idx, col_name in enumerate(columns):
            target_col = btn_cols[idx % 2]
            with target_col:
                if st.button(
                    f"📌 {col_name}",
                    key=f"insert_btn_{col_name}",
                    use_container_width=True,
                    help=f"Insert {{{col_name}}} into the template",
                ):
                    # Append the placeholder to the current template
                    st.session_state.template = (
                        st.session_state.template + f"{{{col_name}}}"
                    )
                    st.rerun()   # Refresh so text_area shows updated value

        st.divider()

        # Quick-copy helper
        if st.session_state.template:
            st.markdown("**🔍 Template Validation**")
            bad = validate_template(st.session_state.template, columns)
            if bad:
                st.warning(
                    f"⚠️ Unknown placeholder(s) found: `{'`, `'.join(bad)}`  \n"
                    "Check for typos — these won't be replaced.",
                    icon="⚠️",
                )
            else:
                st.success("All placeholders match column names.", icon="✅")

    st.divider()

    # ══════════════════════════════════════════════════════════════════════════
    # STEP 3 — Configuration
    # ══════════════════════════════════════════════════════════════════════════
    st.markdown('<p class="step-label">Step 3 — Configure Sending</p>', unsafe_allow_html=True)

    config_cols = st.columns([2, 1], gap="large")

    with config_cols[0]:
        phone_col = st.selectbox(
            "📞 Which column contains the **Parent's Phone Number**?",
            options=columns,
            help=(
                "Numbers should be in international format with country code, "
                "e.g., +919876543210 or 919876543210."
            ),
        )

    with config_cols[1]:
        st.markdown(" ")  # spacer
        st.info(
            f"📋 **{len(df)}** messages will be sent — "
            f"estimated time ≈ **{len(df) * 35 // 60} min {len(df) * 35 % 60} sec**.",
            icon="⏱️",
        )

    st.divider()

    # ══════════════════════════════════════════════════════════════════════════
    # STEP 4 — Live Preview
    # ══════════════════════════════════════════════════════════════════════════
    st.markdown('<p class="step-label">Step 4 — Live Message Preview (First Row)</p>', unsafe_allow_html=True)

    if st.session_state.template.strip():
        preview_message = build_message(st.session_state.template, df.iloc[0])
        preview_phone   = format_phone(df.iloc[0][phone_col])

        preview_cols = st.columns([3, 1], gap="large")
        with preview_cols[0]:
            st.markdown("**Message Preview**")
            st.markdown(
                f'<div class="preview-box">{preview_message}</div>',
                unsafe_allow_html=True,
            )
        with preview_cols[1]:
            st.markdown("**Will be sent to**")
            st.markdown(
                f'<div class="preview-box">{preview_phone}</div>',
                unsafe_allow_html=True,
            )
    else:
        st.info("✏️ Start typing your message template above to see the live preview.", icon="👆")

    st.divider()

    # ══════════════════════════════════════════════════════════════════════════
    # STEP 5 — Send All Reports
    # ══════════════════════════════════════════════════════════════════════════
    st.markdown('<p class="step-label">Step 5 — Send</p>', unsafe_allow_html=True)

    # Pre-send checklist
    ready_to_send = bool(st.session_state.template.strip()) and phone_col

    if not ready_to_send:
        st.warning(
            "⚠️ Please complete the template and select a phone-number column before sending.",
            icon="🔒",
        )

    # ── Send button ──
    st.markdown('<div class="send-btn">', unsafe_allow_html=True)
    send_clicked = st.button(
        "🚀  Send All Reports via WhatsApp",
        disabled=not ready_to_send,
        use_container_width=True,
        key="send_all_btn",
    )
    st.markdown("</div>", unsafe_allow_html=True)

    if send_clicked:
        if not PYWHATKIT_AVAILABLE:
            st.error(
                "🛑 **Cannot send messages from a cloud server.**\n\n"
                "This app uses `pywhatkit` to automate WhatsApp by controlling a local browser and keyboard. "
                "It looks like this app is running on Streamlit Cloud (or a headless server) where there is no display/mouse.\n\n"
                "👉 **To actually send messages, you need to run this app locally on your own computer.**",
                icon="❌"
            )
            st.stop()
            
        # ── Safety confirmation ──
        total = len(df)
        st.warning(
            f"⚠️ You are about to send **{total} WhatsApp messages**.  \n"
            "Make sure **WhatsApp Web is open and logged in** in your default browser.  \n"
            "Do **not** close the browser during the process.",
            icon="🔔",
        )

        confirm = st.checkbox(
            "✅ I confirm — WhatsApp Web is open and I want to proceed.",
            key="confirm_send",
        )

        if confirm:
            # ── Progress tracking ──
            progress_bar     = st.progress(0, text="Preparing to send…")
            status_container = st.empty()
            log_container    = st.container()

            success_count = 0
            fail_count    = 0
            errors        = []

            for i, (_, row) in enumerate(df.iterrows()):
                # Build personalised message
                message = build_message(st.session_state.template, row)
                phone   = format_phone(row[phone_col])

                # Attempt to get a meaningful name for progress display
                name_candidates = [c for c in columns if "name" in c.lower()]
                student_name = row[name_candidates[0]] if name_candidates else f"Row {i + 1}"

                # Update UI
                progress_pct = (i) / total
                progress_bar.progress(
                    progress_pct,
                    text=f"📨 Sending message {i + 1} of {total} — {student_name}…",
                )
                status_container.info(
                    f"**Currently sending:** Report for **{student_name}** → {phone}",
                    icon="📲",
                )

                try:
                    pywhatkit.sendwhatmsg_instantly(
                        phone_no=phone,
                        message=message,
                        wait_time=15,        # seconds to wait for WhatsApp Web to open
                        tab_close=True,      # auto-close the tab after sending
                        close_time=3,        # seconds to wait after sending before closing
                    )
                    success_count += 1
                    with log_container:
                        st.success(f"✅ [{i + 1}/{total}] Sent to **{student_name}** ({phone})", icon="✅")

                except Exception as exc:
                    fail_count += 1
                    error_msg = f"Row {i + 1} ({phone}): {exc}"
                    errors.append(error_msg)
                    with log_container:
                        st.error(f"❌ [{i + 1}/{total}] Failed for **{student_name}** ({phone}) — {exc}")

                # Safety delay between messages (prevents WhatsApp spam-bans)
                if i < total - 1:
                    for remaining in range(20, 0, -1):
                        status_container.info(
                            f"⏳ Cooling down… next message in **{remaining}s** "
                            f"(message {i + 2} of {total})",
                            icon="⏱️",
                        )
                        time.sleep(1)

            # ── Final summary ──
            progress_bar.progress(1.0, text="✅ All messages processed!")
            status_container.empty()

            st.balloons()
            summary_cols = st.columns(3)
            with summary_cols[0]:
                st.metric("Total Sent",   success_count)
            with summary_cols[1]:
                st.metric("Failed",       fail_count)
            with summary_cols[2]:
                st.metric("Total Rows",   total)

            if errors:
                with st.expander("🔴 View failed messages details"):
                    for err in errors:
                        st.code(err)

else:
    # ── No file uploaded yet ──
    st.info(
        "👆 Upload an Excel or CSV file above to get started.",
        icon="📂",
    )
    st.markdown(
        """
        ### What this app does
        - Reads any Excel/CSV sheet containing student marks and parent phone numbers.
        - Lets you craft a **fully customised** WhatsApp message using column names as variables.
        - Sends **personalised messages** to every parent automatically — for free, with no WhatsApp API needed.

        ### Required format (example)

        | Student_Name | Python_Marks | Maths_Marks | Parent_Phone      |
        |--------------|:------------:|:-----------:|-------------------|
        | Alice Sharma | 88           | 92          | +919876543210     |
        | Bob Khan     | 74           | 68          | +919988776655     |
        """,
        unsafe_allow_html=False,
    )
